echo "SIMPLE PATTERN TEST"
echo "==================="
stack --silent runghc Main.hs "Tests/PatternTest.hs"
echo "\nTYPE VARIABLE TEST"
echo "==============="
stack --silent runghc Main.hs "Tests/TypeVariablesTest.hs"
echo "\nNESTED PATTERN TEST"
echo "==================="
stack --silent runghc Main.hs "Tests/NestedPatternTest.hs"
echo "\nDUPLICATE OUTCOME PATTERN TEST"
echo "==================="
stack --silent runghc Main.hs "Tests/PatternDuplicateOutcomeTest.hs"
echo "\nBIG NESTED PATTERN TEST"
echo "==================="
stack --silent runghc Main.hs "Tests/NestedPatternBigTest.hs"
echo "\nINCOMPLETE PATTERN TEST"
echo "==================="
stack --silent runghc Main.hs "Tests/IncompletePatternTest.hs"
echo "\nPARENTHESIS PATTERN TEST"
echo "================"
stack --silent runghc Main.hs "Tests/ParensPatternTest.hs"
echo "\nCASE LEVEL VARIABLE PATTERN TEST"
echo "======================"
stack --silent runghc Main.hs "Tests/CaseLevelVarBindPatternTest.hs"
echo "\nWILDCARD PATTERN TEST"
echo "======================"
stack --silent runghc Main.hs "Tests/WildcardPatternTest.hs"
echo "\nOR PATTERN TEST"
echo "==============="
stack --silent runghc Main.hs "Tests/OrPatternTest.hs"
echo "\nOR PATTERN NESTED TEST"
echo "==============="
stack --silent runghc Main.hs "Tests/OrPatternNestedTest.hs"
echo "\nOR PATTERN SIMPLIFY TEST"
echo "==============="
stack --silent runghc Main.hs "Tests/OrPatternAutoSimplifyTest.hs"
echo "\nOR PATTERN BIG TEST"
echo "==============="
stack --silent runghc Main.hs "Tests/OrPatternBigTest.hs"

echo "\nFAIL ARITY TEST"
echo "================"
stack --silent runghc Main.hs "Tests/FailArityWrongPatternTest.hs"
echo "\nFAIL NON DISTINCT VARIABLES TEST"
echo "================================"
stack --silent runghc Main.hs "Tests/FailNonDistinctPatternTest.hs"
echo "\nFAIL WEIRD PATTERN TEST"
echo "======================="
stack --silent runghc Main.hs "Tests/FailWeirdPatternTest.hs"
echo "\nFAIL OR PATTERN DISTINCT TEST 1"
echo "==============================="
stack --silent runghc Main.hs "Tests/FailOrPatternDistinctTest1.hs"
echo "\nFAIL OR PATTERN DISTINCT TEST 2"
echo "==============================="
stack --silent runghc Main.hs "Tests/FailOrPatternDistinctTest2.hs"
